### Numpy Array Operations

In [3]:
import numpy as np

In [4]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print("Basic Slicing ", arr[2:7])
print("With Step", arr[1:10:2])
print("negative Indexing", arr[-3])


Basic Slicing  [3 4 5 6 7]
With Step [ 2  4  6  8 10]
negative Indexing 8


In [5]:
arr_2d = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])

print("Specific Element" , arr_2d[1,2])
print("Entire Row: ", arr_2d[1])
print("Entire Column: ", arr_2d[:,1])

Specific Element 6
Entire Row:  [4 5 6]
Entire Column:  [2 5 8]


## Sorting

In [6]:
unsorted = np.array([1,23,43,56,41,26,73,12,9,3,0,29,101,234,987,452,542])
print("Sorted Array:",np.sort(unsorted))

arr_2d_unsorted = np.array([[8,3],[4,9],[7,5]])
print("Sorted 2D Array: ", np.sort(arr_2d_unsorted, axis=0)) # Sort by column
print("Sorted 2D Array: ", np.sort(arr_2d_unsorted, axis=1)) # Sort by row

Sorted Array: [  0   1   3   9  12  23  26  29  41  43  56  73 101 234 452 542 987]
Sorted 2D Array:  [[4 3]
 [7 5]
 [8 9]]
Sorted 2D Array:  [[3 8]
 [4 9]
 [5 7]]


## Filter

In [7]:
numbers = np.array([1,2,3,4,5,6,7,8,9,10])
even_number = numbers[numbers % 2 == 0]
print("Even Numbers:", even_number)

Even Numbers: [ 2  4  6  8 10]


In [8]:
mask = numbers > 5
print("Numbers Greater than 5 : ", numbers[mask])


Numbers Greater than 5 :  [ 6  7  8  9 10]


## Fancy Indexing vs np.where()


In [11]:
indices = [0,2,4 ]
print(numbers[indices])

where_result = np.where(numbers > 5)
print(where_result)
print("NP Where", numbers[where_result])



[1 3 5]
(array([5, 6, 7, 8, 9]),)
NP Where [ 6  7  8  9 10]


In [10]:
condition_array = np.where(numbers > 5, "true", "false" )
print(condition_array)

['false' 'false' 'false' 'false' 'false' 'true' 'true' 'true' 'true'
 'true']


### Adding and Removing Data

In [12]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
combined = np.concatenate((arr1,arr2))
print(combined)

[1 2 3 4 5 6]


### Array Compatibility

In [13]:
a = np.array([1,2,3])
b = np.array([4,5,6,12])
c = np.array([7,8,9])

print("Compatibility shapes", a.shape == c.shape)
print("Compatibility shapes", a.shape == b.shape)

Compatibility shapes True
Compatibility shapes False


In [17]:
original = np.array([[1,2],[3,4]])
new_row = np.array([[5,6]])

with_new_row = np.vstack((original, new_row))
print(with_new_row)
print(original)

new_col = np.array([[7],[8]])
with_new_col = np.hstack((original, new_col))
print("with new column:", with_new_col)


[[1 2]
 [3 4]
 [5 6]]
[[1 2]
 [3 4]]
with new column: [[1 2 7]
 [3 4 8]]


In [18]:
arr = np.array([1,2,3,4,5])
deleted = np.delete(arr,2)
print(" Array after Deletion: ", deleted)

 Array after Deletion:  [1 2 4 5]
