In [ ]:
## Learn about Numpy for MLOps
##python env venv 3.8.10 something

In [1]:
import numpy as np

In [4]:
### Creating array from list

In [3]:
arr_1d = np.array([1,2,3,4,5])
print("1D array: ", arr_1d)

arr_2D = np.array([[1,2,3],[4,5,6]])
print("2D array:", arr_2D)


1D array:  [1 2 3 4 5]
2D array: [[1 2 3]
 [4 5 6]]


### List vs Numpy array


In [4]:
py_list = [1,2,3]

print("Python List multiplication ", py_list*2)

np_array = np.array([1,2,3]) # element wise multiplication
print("Python array multiplication ", np_array * 2)

import time 
start = time.time()
py_list = [i*2 for i in range (1000000)]
print("\n List operation time: ", time.time() - start)

start = time.time()
np_array = np.arange(1000000) * 2

print("\n Numpy operation time: ", time.time() - start)

Python List multiplication  [1, 2, 3, 1, 2, 3]
Python array multiplication  [2 4 6]

 List operation time:  0.042634010314941406

 Numpy operation time:  0.0015099048614501953


### Creating Array from Scratch


In [5]:
zeros = np.zeros((3,4))
print("zeros array: \n", zeros)


zeros array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [6]:
ones = np.ones((2,3))
print("ones array: \n", ones)

ones array: 
 [[1. 1. 1.]
 [1. 1. 1.]]


In [7]:
full = np.full((2,2), 7)
print("full array: \n", full)

full array: 
 [[7 7]
 [7 7]]


In [9]:
random = np.random.random((2,3))
print("random array: \n", random)

sequence = np.arange(0,25,2)
print("sequence array: \n", sequence)

random array: 
 [[0.35019201 0.51343098 0.80737366]
 [0.86486564 0.54945264 0.06993873]]
sequence array: 
 [ 0  2  4  6  8 10 12 14 16 18 20 22 24]


### Vector, Matriz and Tensor

In [9]:
vector = np.array([1,2,3])
print("Vector array \n", vector)

matrix = np.array([[1,2,3],[4,5,6]])
print("Matrix array \n", matrix)

tensor = np.array([[[1,2], [3,4]],
                   [[5,6], [7,8]]])
print("Tensor array \n", tensor)

Vector array 
 [1 2 3]
Matrix array 
 [[1 2 3]
 [4 5 6]]
Tensor array 
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Array properties

In [10]:
arr = np.array([[1,2,3],[4,5,6]])
print("Shape of array:" , arr.shape)
print("Dimensions of array:" , arr.ndim)
print("Data type of array:" , arr.dtype)
print("Size of array:" , arr.size)


Shape of array: (2, 3)
Dimensions of array: 2
Data type of array: int64
Size of array: 6


### Array Reshaping 

In [12]:



arr = np.arange(12)
print("Original array: \n", arr)

reshaped = arr.reshape((3,4))
print("Reshaped array: \n", reshaped)

flattened = reshaped.flatten()
print("Flattened array: \n", flattened)
# Ravel returns a flattened array, but it is a view of the original array whenever possible. This means that if you modify the raveled array, it may affect the original array.
raveled = reshaped.ravel()
print("Raveled array: \n", raveled)

Original array: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped array: 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flattened array: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
Raveled array: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
