In [5]:
import numpy as np
import matplotlib.pyplot as plt 

# Data Structure: [restaurant_id, 2021, 2022,2023,2024]
sales_data = np.array([
    [1, 10000, 12000, 15000, 18000],
    [2, 8000, 9000, 11000, 13000],
    [3, 15000, 16000, 17000, 20000],
    [4, 18000, 21000, 24000,27000],
    [5,16000, 18500, 20500,23000]
])

In [34]:
sales_data = np.array([
    [1, 10000, 12000, 15000, 18000],
    [2, 8000, 9000, 49000, 13000],
    [3, 15000, 16000, 17000, 20000],
    [4, 18000, 21000, 20000,27000],
    [5,16000, 18500, 20500,23000]
])

print("=== Sales Data ===")

print(sales_data)
print("\n Sales Data Shape:", sales_data.shape)
print("\n First 3 restaurant data:", sales_data[0:4])

=== Sales Data ===
[[    1 10000 12000 15000 18000]
 [    2  8000  9000 49000 13000]
 [    3 15000 16000 17000 20000]
 [    4 18000 21000 20000 27000]
 [    5 16000 18500 20500 23000]]

 Sales Data Shape: (5, 5)

 First 3 restaurant data: [[    1 10000 12000 15000 18000]
 [    2  8000  9000 49000 13000]
 [    3 15000 16000 17000 20000]
 [    4 18000 21000 20000 27000]]


In [35]:
total_sum = np.sum(sales_data[:, 1:], axis=0)
print("\n Total Sales for each month:", total_sum)
min_sales= np.min(sales_data[:, 1:], axis=0)
print("\n Minimum Sales for each month:", min_sales)

max_sales= np.max(sales_data[:, 1:], axis=0)
print("\n Maximum Sales for each month:", max_sales)


 Total Sales for each month: [ 67000  76500 121500 101000]

 Minimum Sales for each month: [ 8000  9000 15000 13000]

 Maximum Sales for each month: [18000 21000 49000 27000]
